### ISSUE TITLE
Syntax error line 102 

### ISSUE THREAD

**Issue by mizaty** [recitativonika/Dawn-Validator-bot-python#2]

**Comment by mizaty** [comment]
![Uploading Screenshot_20241114-052643.jpg…]()

**Comment by recitativonika** [comment]
are you already do `pip install -r requirements.txt` before running? and can you please show the full error log in the console.

**Comment by mizaty** [comment]
Here is the text from the image you sent:
File "C:\Users\Administrator\Dawn-Validator-bot-python\main.py", line 102

    print(f"Processing: \x1b[36m{email}\x1b[0m, Proxy: {'\x1b [33m' + proxy + '\x1b[0m' if proxy else '\x1b[33mNo Proxy\x1b[0m'}, Points: \x1b[32m{points}\x1b[0m")

SyntaxError: f-string expression part cannot include a backslash



That's the error bos

**Comment by recitativonika** [comment]
thanks give me a sec. I will try to change that

**Comment by recitativonika** [comment]
try pull the repo again
