### ISSUE TITLE
Only running 5 mins and points get 0

### ISSUE THREAD

**Issue by adilrock** [recitativonika/Dawn-Validator-bot-python#4]
I have purchased 100 proxy premium
But the bot only runs about 5 mins only, then script only read 0 points for all my accounts

**Comment by recitativonika** [comment]
Do you put and set all data and proxy properly? I tested it still working with proxy too.

Or do you forgot change the `useProxy: false` to `true` in `config.yaml`?

**Comment by recitativonika** [comment]
I will close this issue page as you not answer the question.
